#ifndef SKYMETRIC_SECRETS_H
#define SKYMETRIC_SECRETS_H

#define BLYNK_TEMPLATE_ID "GANTI_TEMPLATE_ID"
#define BLYNK_TEMPLATE_NAME "GANTI_TEMPLATE_NAME"
#define BLYNK_AUTH_TOKEN "GANTI_AUTH_TOKEN"

#define WIFI_SSID "GANTI_WIFI_SSID"
#define WIFI_PASSWORD "GANTI_WIFI_PASSWORD"

#endif
